package com.orchestranetworks.ps.batch.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX 5.9.0 fix B [1103], at  2019/04/01 11:54:41 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: company-mdm, path: /WEB-INF/ebx/schemas/BatchImportExportDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface BatchImportExportPaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		29 path constants.
	//		18 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_BatchImport
	{
		private static final Path _Root_BatchImport = _Root.add("BatchImport");
		public static Path getPathInSchema()
		{
			return _Root_BatchImport;
		}
		public static final Path _TrackingId = Path.parse("./TrackingId");
		public static final Path _DataSpace = Path.parse("./DataSpace");
		public static final Path _DataSet = Path.parse("./DataSet");
		public static final Path _TablePath = Path.parse("./TablePath");
		public static final Path _FilePath = Path.parse("./FilePath");
		public static final Path _HeaderFormat = Path.parse("./HeaderFormat");
		public static final Path _FieldSeparator = Path.parse("./FieldSeparator");
		public static final Path _CommitThreshold = Path.parse("./CommitThreshold");
		public static final Path _FileType = Path.parse("./FileType");
		public static final Path _FileEncoding = Path.parse("./FileEncoding");
		public static final Path _ImportMode = Path.parse("./ImportMode");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _StartDate = Path.parse("./StartDate");
		public static final Path _EndDate = Path.parse("./EndDate");
		public static final Path _Comment = Path.parse("./Comment");
		public static final Path _Exception = Path.parse("./Exception");
		public static final Path _OrderDate = Path.parse("./OrderDate");
		public static final Path _WorkingDataSpace = Path.parse("./workingDataSpace");
	} 
	// ===============================================

}
