package com.pers.mdm.pers.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 fix C [1067:0007], at  2018/03/21 14:48:57 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: compensar-mdm, path: /WEB-INF/ebx/schemas/PersDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface PersPaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		1 path constants.
	//		0 leaf nodes.
	public static final Path _Root = Path.parse("/root");
	// ===============================================

}
